url: https://starportx.github.io
baseurl: 

# Site settings
title: Starport X
email: starportxxx@hotmail.com
description: "Site Description"



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/starportx598801
  - title: envelope
    url: mailto:starportxxx@hotmail.com
  - title: facebook
    url: https://www.facebook.com/feng.jarod
    

# Postal address (add as many lines as necessary)
address:
  - line: Shanghai China
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty